baseURL = "https://pobe.ga/"
languageCode = "en-us"
title = "Pobega's Blog"
theme = "kiss"
publishDir = "public"
googleAnalytics = ""
disqusShortname = "pobega"
Paginate = 5 #
enableRobotsTXT = true
copyright = "&copy; <a href=\"https://github.com/pobega\">Michael Pobega</a> 2019"

#[params.assets]
#customCSS = ["css/custom.css"]

[params.info]
related = true # Includes related articles at the bottom of the article
codeCopy = true # Add copy button above code blocks

[params.features]
disqusOnDemand = true

[params.social]
twitter = "pobega"
github = "pobega"
email = "pobega@gmail.com"
linkedin = "pobega"

[params.social.config]
platforms = ["github","twitter","linkedin","email"]

[taxonomies]
tag ="tags"
